<?php
/**
 * @file
 * Code for the Blocks.
 */

include_once 'inc/wifi4eu_theme.blocks.inc';
include_once 'inc/wifi4eu_theme_topbar.theme.inc';

/**
 * Implements hook_help().
 *
 * Displays help and module information.
 */
function wifi4eu_theme_help($path, $arg) {
  $output = '';
  switch ($path) {
    case 'admin/help#wifi4eu_theme':
      $output = t('<h3>About</h3><p>The DSM WiFi4EU drive the pages related with
        the WiFi4EU project.</p>');
  }

  return $output;
}
